src/objects/Account_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Express_Multiplier__c</fullName>
        <label>Express Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proofreading_Multiplier__c</fullName>
        <label>Proofreading Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Char_Price__c</fullName>
        <label>Source Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Account_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Word_Price__c</fullName>
        <label>Source Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Char_Price__c</fullName>
        <label>Target Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Account_Pricing1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Word_Price__c</fullName>
        <label>Target Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Urgent_Multiplier__c</fullName>
        <label>Urgent Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Egyedi díjszabás</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>Language_Code__c</fullName>
        <label>Language Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing</label>
        <referenceTo>Pricing__c</referenceTo>
        <relationshipName>Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nyelv</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Language_Pair__c.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Express_Multiplier__c</fullName>
        <label>Express Multiplier</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proofreading_Multiplier__c</fullName>
        <label>Proofreading Multiplier</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Char_Price__c</fullName>
        <label>@DEPR Source Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Word_Price__c</fullName>
        <label>@DEPR Source Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Char_Price__c</fullName>
        <label>@DEPR Target Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Word_Price__c</fullName>
        <label>@DEPR Target Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Translator</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipName>Language_Pairs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Urgent_Multiplier__c</fullName>
        <label>Urgent Multiplier</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Nyelvpár</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Language Pair Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Language Pairs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Region Pricing</relationshipLabel>
        <relationshipName>Region_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Express_Multiplier__c</fullName>
        <label>Express Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing</label>
        <referenceTo>Pricing__c</referenceTo>
        <relationshipLabel>Region Pricing</relationshipLabel>
        <relationshipName>Region_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proofreading_Multiplier__c</fullName>
        <label>Proofreading Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HU</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Char_Price__c</fullName>
        <label>Source Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Word_Price__c</fullName>
        <label>Source Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Char_Price__c</fullName>
        <label>Target Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Word_Price__c</fullName>
        <label>Target Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Urgent_Multiplier__c</fullName>
        <label>Urgent Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Region Pricing</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ügyfél</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Határidő</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Units__c</fullName>
        <label>Mennyiség</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>szóközzel növelt karakter</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>forrásnyelvi szó</fullName>
                </value>
                <value>
                    <fullName>characters</fullName>
                </value>
                <value>
                    <fullName>words</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proofreading__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lektorálva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Alkalmazott díjszabás</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HU</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forrásnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Célnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Határidő</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Language_Pair__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nyelvpár</label>
        <referenceTo>Language_Pair__c</referenceTo>
        <relationshipLabel>Translation Assignments</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Fordítói megbízás</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translation Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Translators</relationshipLabel>
        <relationshipName>Translators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proofreading__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lektorálás</label>
        <type>Checkbox</type>
    </fields>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReflexTests.cls
@isTest
public with sharing class ReflexTests {
	public ReflexTests() {
		initializeCustomSettings();
	}

	public Account[] accountList = new Account[] {};
	public Language__c[] languageList = new Language__c[] {};
	public Pricing__c[] pricingList = new Pricing__c[] {};
	public Region_Pricing__c[] regionPricingList = new Region_Pricing__c[] {};
	public Translator__c[] translatorList = new Translator__c[] {};
	public Translation__c[] translationList = new Translation__c[] {};
	public Language_Pair__c[] languagePairList = new Language_Pair__c[] {};
	public Translation_Assignment__c[] translationAssignmentList = new Translation_Assignment__c[] {};
    public Account_Pricing__c[] accountPricingList = new Account_Pricing__c[] {};
    
    private Sobject getLatestSobject(Sobject[] sobjectList) {
        return sobjectList.isEmpty() ? null : sobjectList[sobjectList.size() - 1];
    }

    public Account getAccount() {
    	return (Account) getLatestSobject(accountList);
    }

    public Language__c getLanguage() {
    	return (Language__c) getLatestSobject(languageList);
    }

    public Pricing__c getPricing() {
    	return (Pricing__c) getLatestSobject(pricingList);
    }

    public Region_Pricing__c getRegionPricing() {
    	return (Region_Pricing__c) getLatestSobject(regionPricingList);
    }
    
    public Translator__c getTranslator() {
    	return (Translator__c) getLatestSobject(translatorList);
    }

    public Translation__c getTranslation() {
    	return (Translation__c) getLatestSobject(translationList);
    }

    public Language_Pair__c getLanguagePair() {
    	return (Language_Pair__c) getLatestSobject(languagePairList);
    }

    public Translation_Assignment__c getTranslationAssignment() {
        return (Translation_Assignment__c) getLatestSobject(translationAssignmentList);
    }

    public Account_Pricing__c getAccountPricing() {
        return (Account_Pricing__c) getLatestSobject(accountPricingList);
    }

    // inserts

    public void insertAccount() {
    	Account a = new Account();
    	a.Name = 'Account Accontovich';
    	insert a;
    	accountList.add(a);
    }

    public void insertLanguage() {
    	Language__c l = new Language__c();
    	l.Name = 'English';
    	l.Language_Code__c = 'EN';
    	l.Pricing__c = getPricing().Id;
    	insert l;
    	languageList.add(l);
    }

    public void insertPricing() {
    	Pricing__c p = new Pricing__c();
    	p.Name = 'myPricing1';
    	insert p;
    	pricingList.add(p);
    }

    public void insertRegionPricing() {
    	Region_Pricing__c rp = new Region_Pricing__c();
    	rp.Pricing__c = getPricing().Id;
    	rp.Region__c = 'HU';
    	rp.Base_Price__c = 1000;
    	rp.Source_Char_Price__c = 1;
    	rp.Target_Char_Price__c = 1;
    	rp.Source_Word_Price__c = 1;
    	rp.Target_Word_Price__c = 1;
    	rp.Urgent_Multiplier__c = 30;
     	rp.Express_Multiplier__c = 30;
     	rp.Proofreading_Multiplier__c = 30;
     	insert rp;
     	regionPricingList.add(rp);
    }
    
    public void insertAccountPricing() {
    	Account_Pricing__c a = new Account_Pricing__c();
    	a.Source_Language__c = getLanguage().Id;
    	a.Target_Language__c = getLanguage().Id;
        
    	insert a;
    	accountPricingList.add(a);
    }

    public void insertTranslation() {
    	Translation__c t = new Translation__c();
    	t.Account__c = getAccount().Id;
    	t.Estimated_Count__c = 3000;
    	t.Estimated_Units__c = ReflexSettings.TRANSLATION_UNIT_CHAR;
    	t.Source_Language__c = languageList[languageList.size()-1].Id;
    	t.Target_Language__c = languageList[languageList.size()-2].Id;
    	t.Due_Date__c = Datetime.Now() + 5;
    	insert t;
    	translationList.add(t);
    }

    public void insertTranslator() {
    	Translator__c t = new Translator__c();
    	t.Name = 'The Translator';
    	t.Proofreading__c = true;
    	t.Editor__c = true;
    	insert t;
    	translatorList.add(t);
    }

    public void insertTranslationAssignment() {
    	Translation_Assignment__c tra = new Translation_Assignment__c();
    	tra.Translation__c = getTranslation().Id;
    	tra.Translator__c = getTranslator().Id;
    	insert tra;
    	translationAssignmentList.add(tra);
    }

    public void insertLanguagePair() {
    	Language_Pair__c lp = new Language_Pair__c();
    	lp.Translator__c = getTranslator().id;
    	lp.From__c = languageList[languageList.size()-1].Id;
    	lp.To__c = languageList[languageList.size()-2].Id;
    	insert lp;
    	languagePairList.add(lp);
    }

    // initializers
    public void initializeLanguageWithPricing() {
		insertPricing();
		insertRegionPricing();
		insertLanguage();
    }
    public void initializeCustomSettings() {
    	ReflexSettings.setSettingValue('DAYS_BEFORE_DUE_DATE', '2');
    	ReflexSettings.setSettingValue('MAXIMUM_CHARS_PER_DAY', '6000');
		ReflexSettings.setSettingValue('MAXIMUM_CHARS_PER_DAY_URGENT', '12000');
		ReflexSettings.setSettingValue('MAXIMUM_WORDS_PER_DAY', '500');
		ReflexSettings.setSettingValue('MAXIMUM_WORDS_PER_DAY_URGENT', '1000');
		ReflexSettings.setSettingValue('MINIMUM_CUSTOMER_PRICE_HU', '1000');
		ReflexSettings.setSettingValue('MINIMUM_CUSTOMER_PRICE_INT', '20');
    }

    public void initializeTranslation() {
		initializeLanguageWithPricing();
		insertLanguage();
		insertAccount();
		insertTranslation(); 	
    }

    // asserts
 	public void assertLanguageCount(Integer expectedCount) {
        system.assertEquals(expectedCount, [
            SELECT count()
              FROM Language__c
             WHERE Id in :languageList
        ]);
    }

 	public void assertPricingCount(Integer expectedCount) {
        system.assertEquals(expectedCount, [
            SELECT count()
              FROM Pricing__c
             WHERE Id in :pricingList
        ]);
    }

 	public void assertRegionPricingCount(Integer expectedCount) {
        system.assertEquals(expectedCount, [
            SELECT count()
              FROM Region_Pricing__c
             WHERE Id in :regionPricingList
        ]);
    }

 	public void assertAccountCount(Integer expectedCount) {
        system.assertEquals(expectedCount, [
            SELECT count()
              FROM Account
             WHERE Id in :accountList
        ]);
    }   

 	public void assertTranslationCount(Integer expectedCount) {
        system.assertEquals(expectedCount, [
            SELECT count()
              FROM Translation__c
             WHERE Id in :translationList
        ]);
    }  
}