src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Translation_Discount__c</fullName>
        <label>Díjkedvezmény</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translation_Surcharge__c</fullName>
        <label>Felár</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Account_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Express_Multiplier__c</fullName>
        <label>Express Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proofreading_Multiplier__c</fullName>
        <label>Proofreading Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Char_Price__c</fullName>
        <label>Source Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Account_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Word_Price__c</fullName>
        <label>Source Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Char_Price__c</fullName>
        <label>Target Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Target Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Account_Pricing1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Word_Price__c</fullName>
        <label>Target Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Urgent_Multiplier__c</fullName>
        <label>Urgent Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Egyedi díjszabás</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <fields>
        <fullName>Pricing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing</label>
        <referenceTo>Pricing__c</referenceTo>
        <relationshipName>Languages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Nyelv</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Language_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language From</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Pricing</relationshipLabel>
        <relationshipName>Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Language To</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Pricing (Language To)</relationshipLabel>
        <relationshipName>Pricing1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Region Pricing</relationshipLabel>
        <relationshipName>Region_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Express_Multiplier__c</fullName>
        <label>Express Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing</label>
        <referenceTo>Pricing__c</referenceTo>
        <relationshipLabel>Region Pricing</relationshipLabel>
        <relationshipName>Region_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proofreading_Multiplier__c</fullName>
        <label>Proofreading Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HU</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Char_Price__c</fullName>
        <label>Source Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_Word_Price__c</fullName>
        <label>Source Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Char_Price__c</fullName>
        <label>Target Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Word_Price__c</fullName>
        <label>Target Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Urgent_Multiplier__c</fullName>
        <label>Urgent Multiplier</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Region Pricing</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ügyfél</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Translations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hitelesítve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Proofreading__c</fullName>
        <defaultValue>true</defaultValue>
        <label>@DEPR Lektorálás esetén van felár</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Urgent__c</fullName>
        <defaultValue>true</defaultValue>
        <label>@DEPR Sürgős/expressz esetén van felár</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Határidő</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Units__c</fullName>
        <label>Mennyiség</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>szóközzel növelt karakter</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>forrásnyelvi szó</fullName>
                </value>
                <value>
                    <fullName>characters</fullName>
                </value>
                <value>
                    <fullName>words</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Express__c</fullName>
        <defaultValue>false</defaultValue>
        <label>@DEPR Expressz</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Szakterület</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGR</fullName>
                </value>
                <value>
                    <fullName>BIZT</fullName>
                </value>
                <value>
                    <fullName>ELEKTR</fullName>
                </value>
                <value>
                    <fullName>ÉLELM</fullName>
                </value>
                <value>
                    <fullName>ENERG</fullName>
                </value>
                <value>
                    <fullName>ÉPIP</fullName>
                </value>
                <value>
                    <fullName>EÜ</fullName>
                </value>
                <value>
                    <fullName>PÜ</fullName>
                </value>
                <value>
                    <fullName>GAZD</fullName>
                </value>
                <value>
                    <fullName>GÉPIP</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JOG</fullName>
                </value>
                <value>
                    <fullName>KÖRNY</fullName>
                </value>
                <value>
                    <fullName>KÖZL</fullName>
                </value>
                <value>
                    <fullName>KULT</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SZÁLL</fullName>
                </value>
                <value>
                    <fullName>OKIRAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lock_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Akkor jelöld be, ha az ajánlatádásnál végleges vállalási árat adsz meg, ami független a fordítás tényleges mennyiségétől.</inlineHelpText>
        <label>@DEPR Az ajánlati ár végleges</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Native_Language_Proofreading__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Anyanyelvi lektorálással</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price_Based__c</fullName>
        <label>Elszámolási egység</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Source</fullName>
                </value>
                <value>
                    <fullName>Target</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proofreading_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Akkor kell bejelölni, ha a megrendelés idegen fordítás vagy magyar szöveg lektorálására szól, fordítás nélkül.</inlineHelpText>
        <label>Csak lektorálást kér</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proofreading__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lektorálva</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Alkalmazott díjszabás</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HU</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forrásnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Célnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Urgent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>@DEPR Sürgős</label>
        <type>Checkbox</type>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Translation_EstimatePrice.cls
// @@ DEPRECATED
// the last update statement is commented out
public class Translation_EstimatePrice extends TranslationTrigger {
    public static final string TRANSLATION_UNIT_CHAR = ReflexSettings.TRANSLATION_UNIT_CHAR;
    public static final string TRANSLATION_UNIT_WORD = ReflexSettings.TRANSLATION_UNIT_WORD;

    public Map <id, Language__c> languagesMap;
    public Map <Id, Pricing__c> pricingMap = new Map <id, Pricing__c>();
	public Map <String, Pricing__c> pricingPairsMap = new map <String, Pricing__c>();
    public Map <Id, Account> accountMap;
    public Map <Id, Account_Pricing__c[]> accountPricing;
    
    public Translation_EstimatePrice(Translation__c[] sobjectOldList, Translation__c[] sobjectNewList) {
        super(sobjectOldList, sobjectNewList);
    }    
	
    public override Boolean getIsMatching(Translation__c sobjectOld, Translation__c sobjectNew) {
    	
        if (sobjectNew.Target_Language__c == null) {   sobjectNew.addError('Please set the Language To field'); return false;}    	
        if (sobjectNew.Source_Language__c == null) { sobjectNew.addError('Please set the Language From field'); return false;}
    

        // if the price is locked, we dont do anything
        if (sobjectNew.Lock_Price__c) {
        	return false;
        }
        
        // if this is a new tranlastion we are going on
        if (sobjectOld == null) {
        	return true;
        }

        if (sobjectOld.Lock_Price__c == true) {
            return false;
        }

        return sobjectOld.Account__c != sobjectNew.Account__c  || 
                sobjectOld.Source_Language__c != sobjectNew.Source_Language__c  ||
                sobjectOld.Target_Language__c != sobjectNew.Target_Language__c ||
                sobjectOld.Estimated_Count__c != sobjectNew.Estimated_Count__c ||
                sobjectOld.Estimated_Units__c != sobjectNew.Estimated_Units__c ||
                sobjectOld.Urgent__c != sobjectNew.Urgent__c ||
                sobjectOld.Express__c != sobjectNew.Express__c ||
                sobjectOld.Proofreading__c != sobjectNew.Proofreading__c ||
                sobjectOld.Native_Language_Proofreading__c != sobjectNew.Native_Language_Proofreading__c ||
                sobjectOld.Proofreading_Only__c != sobjectNew.Proofreading_Only__c ||
                sobjectOld.Region__c != sobjectNew.Region__c ||
                sobjectOld.Due_Date__c != sobjectNew.Due_Date__c ||
                sobjectOld.Charge_Urgent__c != sobjectNew.Charge_Urgent__c || 
                sobjectOld.Charge_Proofreading__c != sobjectNew.Charge_Proofreading__c ||
                sobjectOld.Price_Based__c != sobjectNew.Price_Based__c ||
                sobjectOld.Field__c != sobjectNew.Field__c ||
                sobjectOld.Certified__c != sobjectNew.Certified__c
                ;
    }

    public override void execute(Translation__c[] sobjectList, Boolean doUpdate) {
		languagesMap = new map <id, Language__c>([SELECT Name
                                             ,Pricing__c
                                             ,Pricing__r.Name                          
                                             FROM Language__c
                                             LIMIT 10000]);                        

        pricingMap = new Map<Id, Pricing__c>([SELECT Name
                                        ,Language_From__c
                                        ,Language_To__c
                                        ,(SELECT Name 
                                            , Base_Price__c
                                            , Source_Char_Price__c
                                            , Source_Word_Price__c
                                            , Express_Multiplier__c
                                            , Proofreading_Multiplier__c
                                            , Region__c
                                            , Target_Char_Price__c
                                            , Target_Word_Price__c
                                            , Urgent_Multiplier__c
                                            FROM Region_Pricing__r)
                                        FROM Pricing__c LIMIT 10000]); 

        accountMap = new Map<Id, Account>([SELECT Name
                                                ,Translation_Discount__c
                                                ,Translation_Surcharge__c
                                                FROM Account WHERE
                                                Id IN (
                                                    SELECT Account__c 
                                                    FROM Translation__c
                                                    WHERE Id IN : sobjectList)
                                            ]);                      
        // getting the custom account pricing
        accountPricing = new Map <Id, Account_Pricing__c[]>();
        for (Account_Pricing__c ap : [SELECT Name 
                                                , Account__c
	                                            , Base_Price__c
	                                            , Source_Char_Price__c
	                                            , Source_Word_Price__c
	                                            , Express_Multiplier__c
	                                            , Proofreading_Multiplier__c
	                                            , Source_Language__c
	                                            , Target_Char_Price__c
	                                            , Target_Word_Price__c
	                                            , Target_Language__c
	                                            , Urgent_Multiplier__c
	                                            FROM Account_Pricing__c
	                                            WHERE Account__c != null]) {
	        if (accountPricing.containsKey(ap.Account__c) ) {
	        	accountPricing.get(ap.Account__c).add(ap);
	        }                                       	
	        else {
	        	accountPricing.put(ap.Account__c, new Account_Pricing__c[]{ap});
	        }
        }
	                                            
        // storing here the exact pairs                        
		for (Pricing__c pricing : pricingMap.values()) {
			if (pricing.Language_From__c != null && pricing.Language_To__c != null) {
				pricingPairsMap.put((String) pricing.Language_From__c + '|' + (String) pricing.Language_To__c, pricing); 
			}
		}
        
        for (Translation__c estimate : sobjectList) {
        	// some adjustments
        	if (estimate.Estimated_Count__c == null) {
        		estimate.Estimated_Count__c = 0;
        	}
            if (estimate.Due_Date__c == null) {
                estimate.Due_Date__c = DateTime.Now() + ReflexSettings.DEFAULT_DUE_DATE;
            }
                    	
            //setting the currency
            if (estimate.Region__c == null) {
                estimate.addError('Please set a Region.');
                continue;
            }
            estimate.Currency__c = ReflexSettings.getSettingValue('CURRENCY_CODE_' + estimate.Region__c);

            //estimating the completion due date
            Integer unitPerDay = 99999999;
            Integer unitPerDayUrgent = 99999999;
            if (estimate.Estimated_Units__c == ReflexSettings.TRANSLATION_UNIT_CHAR) {
                unitPerDay = Integer.ValueOf(ReflexSettings.getSettingValue('MAXIMUM_CHARS_PER_DAY'));
                unitPerDayUrgent = Integer.ValueOf(ReflexSettings.getSettingValue('MAXIMUM_CHARS_PER_DAY_URGENT'));   
            }
            if (estimate.Estimated_Units__c == ReflexSettings.TRANSLATION_UNIT_WORD) {
                unitPerDay = Integer.ValueOf(ReflexSettings.getSettingValue('MAXIMUM_WORDS_PER_DAY'));
                unitPerDayUrgent = Integer.ValueOf(ReflexSettings.getSettingValue('MAXIMUM_WORDS_PER_DAY_URGENT'));  
            }

            Decimal normalDays = Integer.valueOf(math.Ceil(estimate.Estimated_Count__c / unitPerDay));
            Decimal urgentDays = Integer.valueOf(math.Ceil(estimate.Estimated_Count__c / unitPerDayUrgent));
            //if there is proofreading, we are working 1,5 times slower
            if (estimate.Proofreading__c) {
                normalDays = math.Ceil(normalDays * 1.5);
                urgentDays = math.Ceil(urgentDays * 1.5);
            }

            estimate.Estimated_Due_Date__c = workingDaysFrom(Date.Today(), normalDays); 
            
            Date estimatedUrgentDate = workingDaysFrom(Date.Today(), urgentDays); 
            // setting express / urgent
            if (estimate.Due_Date__c != null) {
                if (estimate.Due_Date__c < estimate.Estimated_Due_Date__c) {
                    if(estimate.Due_Date__c < estimatedUrgentDate) {
                        estimate.Express__c = true;
                        estimate.Urgent__c = false;
                    }
                    else {
                        estimate.Urgent__c = true;
                        estimate.Express__c = false;
                    }
                }
            }

            //calculating the price
            String myKey = (String) estimate.Source_Language__c + '|' + (String) estimate.Target_Language__c;
            Region_Pricing__c myRegionPricing;
            Boolean customPricing = false;
            
            // if there are some custom pricing for this account
            if (accountPricing.containsKey(estimate.Account__c)) {
            	//looking up the exact language pair
            	for (Account_Pricing__c ap : AccountPricing.get(estimate.Account__c)) {
            		if (ap.Source_Language__c == estimate.Source_Language__c && ap.Target_Language__c == estimate.Target_Language__c) {
                        myRegionPricing = new Region_Pricing__c();
                        myRegionPricing.Base_Price__c = ap.Base_Price__c;
                        myRegionPricing.Express_Multiplier__c = ap.Express_Multiplier__c;
                        myRegionPricing.Proofreading_Multiplier__c = ap.Proofreading_Multiplier__c;
                        myRegionPricing.Source_Char_Price__c = ap.Source_Char_Price__c;
                        myRegionPricing.Source_Word_Price__c = ap.Source_Word_Price__c;
                        myRegionPricing.Target_Char_Price__c = ap.Target_Char_Price__c;
                        myRegionPricing.Target_Word_Price__c = ap.Target_Word_Price__c;
                        myRegionPricing.Urgent_Multiplier__c = ap.Urgent_Multiplier__c;
                        customPricing = true;
                        break;    			
            		}
            	}
            }
            // else we look for the price for the language pair
            if (myRegionPricing == null && pricingPairsMap.containsKey(myKey)) {
	            for (Region_Pricing__c regionPricing : pricingPairsMap.get(myKey).Region_Pricing__r) {
	                if (regionPricing.Region__c == estimate.Region__c) {
	                	myRegionPricing = regionPricing;
	                	break;
	                }
	            }
            }
            
            if (estimate.Price_Based__c == null && estimate.Region__c == 'HU') {
            	estimate.Price_Based__c = ReflexSettings.PRICE_BASED_TARGET;
            }

            if (estimate.Price_Based__c == null && estimate.Region__c == 'INT') {
                estimate.Price_Based__c = ReflexSettings.PRICE_BASED_SOURCE;
            }
            
            // if proofreading or NLP is true, we set proofreading to true
            priceEstimate priceEstimate = new priceEstimate(myRegionPricing, 
                    estimate.Estimated_Count__c, 
                    estimate.Estimated_Units__c, 
                    estimate.Proofreading__c || estimate.Native_Language_Proofreading__c,  // OR
                    estimate.Urgent__c, 
                    estimate.Express__c,
                    estimate.Price_Based__c);
            
            // checking, if we charge everthinh, or only the base price
            Decimal calculatedPrice;
            if (estimate.Charge_Proofreading__c && estimate.Charge_Urgent__c) {
                calculatedPrice = priceEstimate.totalPrice();
            } else if (!estimate.Charge_Proofreading__c && estimate.Charge_Urgent__c) {
                calculatedPrice = priceEstimate.basePrice + 
                                  priceEstimate.urgentPrice +
                                  priceEstimate.expressPrice;
            } else if (estimate.Charge_Proofreading__c && !estimate.Charge_Urgent__c) {
                calculatedPrice = priceEstimate.basePrice + 
                                  priceEstimate.proofreadingPrice;
            } else if (!estimate.Charge_Proofreading__c && !estimate.Charge_Urgent__c) {
                calculatedPrice = priceEstimate.basePrice;
            }
            // adding some, if there is a certified multiplier applied
            if (estimate.Certified__c) {
            	calculatedPrice *= (1 + defaultZero(Decimal.valueOf(ReflexSettings.getSettingValue('CERTIFIED_MULTIPLIER'))) / 100);
            }
            // the proofreading-only option
            if (estimate.Proofreading_Only__c) {
            	calculatedPrice = priceEstimate.basePrice * 
            	   defaultZero(Decimal.valueOf(ReflexSettings.getSettingValue('PROOFREADING_ONLY_MULTIPLIER'))) / 100;
            }
            
            // looking for field-specied multipliers
            if (ReflexSettings.getSettingValue('FIELD_MULTI__' + estimate.Field__c) != null) {
            	calculatedPrice *= Decimal.valueOf(ReflexSettings.getSettingValue('FIELD_MULTI__' + estimate.Field__c));
            }
            
            // applying account discount and surcharge (if there is no custom pricing applied)
            if (accountMap.containsKey(estimate.Account__c) && !customPricing) {
            	calculatedPrice *= 1 
            	                   - defaultZero(accountMap.get(estimate.Account__c).Translation_Discount__c) / 100
                                   + defaultZero(accountMap.get(estimate.Account__c).Translation_Surcharge__c) / 100;
            }       
            
            // setting the company-wide minimal
            Decimal minPrice = defaultOf(Decimal.valueOf(ReflexSettings.getSettingValue('MINIMUM_CUSTOMER_PRICE_' + estimate.Region__c)),0);
            
            //estimate.Estimated_Price__c =  calculatedPrice < minPrice ? minPrice : calculatedPrice;
        }
    }

    public class priceEstimate {
        public Decimal basePrice;
        public Decimal proofreadingPrice;
        public Decimal urgentPrice;
        public Decimal expressPrice;
        
        public priceEstimate(Region_Pricing__c regionPricing,
                    Decimal unitCount,
                    String unitType, 
                    Boolean proofreading, 
                    Boolean urgent, 
                    Boolean express,
                    String priceBased
                    ) 
        {
                  	
            if (regionPricing == null) {
                this.basePrice = 0;
                this.proofreadingPrice = 0;
                this.urgentPrice = 0;
                this.expressPrice = 0;
                return;
            }      	
            // the baseprice
            
            
            decimal myUnitPrice;
            if (unitType == ReflexSettings.TRANSLATION_UNIT_CHAR) {
            	if (priceBased == ReflexSettings.PRICE_BASED_SOURCE) {
            	    myUnitPrice = defaultZero(regionPricing.Source_Char_Price__c);
            	} else {
                    myUnitPrice = defaultZero(regionPricing.Target_Char_Price__c);
            	}
            }
            if (unitType == ReflexSettings.TRANSLATION_UNIT_WORD) {
            	if (priceBased == ReflexSettings.PRICE_BASED_SOURCE) {
                    myUnitPrice = defaultZero(regionPricing.Source_Word_Price__c);
            	} else {
            		myUnitPrice = defaultZero(regionPricing.Target_Word_Price__c);
            	}
            }
            
            this.basePrice = defaultZero(regionPricing.Base_Price__c)
                            + defaultZero(unitCount) * defaultZero(myUnitPrice);
            // the proofreading price
            if (proofreading) {
            	this.proofreadingPrice = basePrice * (defaultZero(regionPricing.Proofreading_Multiplier__c)/100);
            } else {
            	this.proofreadingPrice = 0;
            }

            // the proofreading price
            if (urgent) {
                this.urgentPrice = basePrice * (defaultZero(regionPricing.Urgent_Multiplier__c)/100);
            } else {
                this.urgentPrice = 0;
            }

            // the express price
            if (express) {
                this.expressPrice = basePrice * (defaultZero(regionPricing.Express_Multiplier__c)/100);
            } else {
                this.expressPrice = 0;
            }
                    	
        }
        
        public Decimal totalPrice() {
            return this.basePrice
                 + this.proofreadingPrice
                 + this.urgentPrice
                 + this.expressPrice;
        }  

	    private decimal defaultZero(Decimal value) {
	        return value != null ? value : 0;
	    }
    }

    public Date workingDaysFrom(Date d, Decimal n) {
    	system.debug('+++ N: ' + n);
        Integer days = 0;
        Integer workDays = 0;
        do {
        	days ++;
        	system.debug('+++ ' + (d+days) + ' --- ' + dayOfWeek(d + days));
            if (dayOfWeek(d + days) != 0 && dayOfWeek(d + days) != 6) {
                workDays ++;  
            }  
                 	
        } while (workDays < n);
  
        return d + days;
    }

    //returns day of the week for a given date. 0-sunday, 1-monday....
    public Integer dayOfWeek(Date d) {
        return Math.mod(Date.NewInstance(1984, 1, 1).daysBetween(d), 7);
    }
           

}