src/objects/Fixer_Rates__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>EUR_to_HUF__c</fullName>
        <label>EUR to HUF</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Fixer Rates</label>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Current_EUR_To_HUF__c</fullName>
        <label>Jelenlegi EUR Árfolyam</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Price_Eur__c</fullName>
        <label>Nettó ajánlati ár EUR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Price__c</fullName>
        <label>Nettó ajánlati ár</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Translation_CurrencyRate.cls
public with sharing class Translation_CurrencyRate extends TriggerClass {

	public static Boolean disableTrigger = false;

    public override Boolean getIsToProcess(SObject sObjectOld, SObject sObjectNew) {
		if (disableTrigger == true) return false;

		return sObjectOld.get('Estimated_Price__c') != sObjectNew.get('Estimated_Price__c')
		//|| sObjectOld.get('Estimated_Price_EUR__c') != sObjectNew.get('Estimated_Price_EUR__c')
		;
	}	

	public override void executeTrigger(SObject[] sObjectList) {

		Translation_CurrencyRate.disableTrigger = true; // run only once

		Fixer_Rates__c rates = Fixer_Rates__c.getOrgDefaults();
		if (rates == null) return;
		if (rates.EUR_to_HUF__c == null) return;

		for (Translation__c tra : (Translation__c[]) sObjectList) {
			// HUF updated
			if (tra.Estimated_Price__c != null && 
				(
					Trigger.isInsert
					||
					tra.Estimated_Price__c != Trigger.oldMap.get(Tra.Id).get('Estimated_Price__c')
				)) 
			{
				tra.Estimated_Price_EUR__c = tra.Estimated_Price__c / rates.EUR_to_HUF__c;
				tra.Current_EUR_To_HUF__c = rates.EUR_to_HUF__c;
			} 
			// EUR updated
			else if (tra.Estimated_Price_EUR__c != null &&
				(
					Trigger.isInsert
					||
					tra.Estimated_Price_EUR__c != Trigger.oldMap.get(Tra.Id).get('Estimated_Price_EUR__c')

				)) 
			{
				tra.Estimated_Price__c = tra.Estimated_Price_EUR__c * rates.EUR_to_HUF__c;
				tra.Current_EUR_To_HUF__c = rates.EUR_to_HUF__c;
			}
		}

	}
}