src/objects/Language_Pair__c.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Char_Price__c</fullName>
        <label>Char Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGR</fullName>
                </value>
                <value>
                    <fullName>BIZT</fullName>
                </value>
                <value>
                    <fullName>ELEKTR</fullName>
                </value>
                <value>
                    <fullName>ÉLELM</fullName>
                </value>
                <value>
                    <fullName>ENERG</fullName>
                </value>
                <value>
                    <fullName>ÉPIP</fullName>
                </value>
                <value>
                    <fullName>EÜ</fullName>
                </value>
                <value>
                    <fullName>PÜ</fullName>
                </value>
                <value>
                    <fullName>GAZD</fullName>
                </value>
                <value>
                    <fullName>GÉPIP</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JOG</fullName>
                </value>
                <value>
                    <fullName>KÖRNY</fullName>
                </value>
                <value>
                    <fullName>KÖZL</fullName>
                </value>
                <value>
                    <fullName>KULT</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SZÁLL</fullName>
                </value>
                <value>
                    <fullName>OKIRAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Language_Pairs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proofreading_Multiplier__c</fullName>
        <label>Proofreading Multiplier</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Language_Pairs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Translator</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipName>Language_Pairs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Word_Price__c</fullName>
        <label>Word Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Nyelvpár</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Language Pair Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Language Pairs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Units__c</fullName>
        <label>Mennyiség</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>szóközzel növelt karakter</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>forrásnyelvi szó</fullName>
                </value>
                <value>
                    <fullName>characters</fullName>
                </value>
                <value>
                    <fullName>words</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Szakterület</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGR</fullName>
                </value>
                <value>
                    <fullName>BIZT</fullName>
                </value>
                <value>
                    <fullName>ELEKTR</fullName>
                </value>
                <value>
                    <fullName>ÉLELM</fullName>
                </value>
                <value>
                    <fullName>ENERG</fullName>
                </value>
                <value>
                    <fullName>ÉPIP</fullName>
                </value>
                <value>
                    <fullName>EÜ</fullName>
                </value>
                <value>
                    <fullName>PÜ</fullName>
                </value>
                <value>
                    <fullName>GAZD</fullName>
                </value>
                <value>
                    <fullName>GÉPIP</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JOG</fullName>
                </value>
                <value>
                    <fullName>KÖRNY</fullName>
                </value>
                <value>
                    <fullName>KÖZL</fullName>
                </value>
                <value>
                    <fullName>KULT</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SZÁLL</fullName>
                </value>
                <value>
                    <fullName>OKIRAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forrásnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Célnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Feladat</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Translating</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Proofreading</fullName>
                </value>
                <value>
                    <fullName>Editing</fullName>
                </value>
                <value>
                    <fullName>Supervising</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Fordítói megbízás</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translation Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Szakterületek</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGR</fullName>
                </value>
                <value>
                    <fullName>BIZT</fullName>
                </value>
                <value>
                    <fullName>ELEKTR</fullName>
                </value>
                <value>
                    <fullName>ÉLELM</fullName>
                </value>
                <value>
                    <fullName>ENERG</fullName>
                </value>
                <value>
                    <fullName>ÉPIP</fullName>
                </value>
                <value>
                    <fullName>EÜ</fullName>
                </value>
                <value>
                    <fullName>PÜ</fullName>
                </value>
                <value>
                    <fullName>GAZD</fullName>
                </value>
                <value>
                    <fullName>GÉPIP</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JOG</fullName>
                </value>
                <value>
                    <fullName>KÖRNY</fullName>
                </value>
                <value>
                    <fullName>KÖZL</fullName>
                </value>
                <value>
                    <fullName>KULT</fullName>
                </value>
                <value>
                    <fullName>SAP</fullName>
                </value>
                <value>
                    <fullName>SZÁLL</fullName>
                </value>
                <value>
                    <fullName>OKIRAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minimum_Wage__c</fullName>
        <label>Minimális díj (alapár)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TranslationAssignment_UpdatePrice.cls
public with sharing class TranslationAssignment_UpdatePrice extends TriggerClass {

    public override Boolean getIsToProcess(SObject sObjectOld, SObject sObjectNew) {
		return sObjectOld.get('Estimated_Count__c') != sObjectNew.get('Estimated_Count__c')
			|| sObjectOld.get('Task__c') != sObjectNew.get('Task__c')
			;
	}	

	public override void executeTrigger(SObject[] sObjectList) {
		
		Translation_Assignment__c[] taList = [SELECT Name
													, Estimated_Count__c
													, Task__c
													, Translator__c
													, Translator__r.Name
													, Translator__r.Char_Price__c
													, Translator__r.Word_Price__c
													, Translator__r.Minimum_Wage__c
													, Translation__c
													, Translation__r.Estimated_Units__c
													, Translation__r.Estimated_Count__c
													, Translation__r.Field__c
													, Translation__r.Source_Language__c
													, Translation__r.Target_Language__c
												FROM Translation_Assignment__c
												WHERE Id IN :sObjectList];

		Set<Id> traIdSet = new Set<Id>{};
		for (Translation_Assignment__c ta : taList) {
			if (ta.Translator__c == null) continue;
			traIdSet.add(ta.Translator__c);
		}
		
		Map<Id, Translator__c> traMap = new Map<Id, Translator__c>([SELECT Name
																, Char_Price__c
																, Word_Price__c
																, Minimum_Wage__c
																, (SELECT Base_Price__c
																		, Char_Price__c
																		, Field__c
																		, From__c
																		, To__c
																		, Word_Price__c
																		, Proofreading_Multiplier__c
																	FROM Language_Pairs__r)
															FROM Translator__c
															WHERE Id IN :traIdSet]);




		for (Translation_Assignment__c ta : taList) {
			ta = TranslationAssignmentService.calculatePrice(ta, traMap.get(ta.Translator__c));
		}

		update taList;
	}
}