src/objects/Language__c.object
<CustomObject>
    <label>Nyelv</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <label>@DEPR Teljesítési státusz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nyitva</fullName>
                </value>
                <value>
                    <fullName>Fordítónak kiadva</fullName>
                </value>
                <value>
                    <fullName>Lektornak kiadva</fullName>
                </value>
                <value>
                    <fullName>Megrendelőnek leszállítva</fullName>
                </value>
                <value>
                    <fullName>Visszautasítva</fullName>
                </value>
                <value>
                    <fullName>Megrendelés törölve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Határidő</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Units__c</fullName>
        <label>Mennyiség</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>szóközzel növelt karakter</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>forrásnyelvi szó</fullName>
                </value>
                <value>
                    <fullName>characters</fullName>
                </value>
                <value>
                    <fullName>words</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No translators available</fullName>
                </value>
                <value>
                    <fullName>Not expensive enough</fullName>
                </value>
                <value>
                    <fullName>Too much text</fullName>
                </value>
                <value>
                    <fullName>Unable to complete in deadline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Forrásnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Language__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Célnyelv</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipName>Translations_By_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <label>Megbízási státusz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kiadva</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Teljesítve</fullName>
                </value>
                <value>
                    <fullName>Megrendelés visszavonva</fullName>
                </value>
                <value>
                    <fullName>Megreklamálva</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Documents__c</fullName>
        <label>Dokumentumok</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Határidő</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Üzenet</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Postpaid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fizetés utólag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>A reklamáció oka</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Feladat</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Translating</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Proofreading</fullName>
                </value>
                <value>
                    <fullName>Editing</fullName>
                </value>
                <value>
                    <fullName>Supervising</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Translator_Price__c</fullName>
        <label>Fordítói díj</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Fordítói megbízás</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translation Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TranslationAssignment_DocumentList.cls
public without sharing class TranslationAssignment_DocumentList {
    public Translation_Assignment__c translationAssignment {get; set;}
    public Document[] documentList {get; set;}
    public String chatterMessage {get; set;}
    
    public TranslationAssignment_DocumentList() {}
    
    public void initialize() {
        String id = ApexPages.currentPage().getParameters().get('id');
        initializeTranslationAssignment(id);
        intializeDocumentList();
    }   


    public void initializeTranslationAssignment(Id id) {
        translationAssignment = [SELECT Name
                                    ,Assignment_Status__c
                                    ,Documents__c
                                    ,Due_Date__c
                                    ,Message__c
                                    ,Postpaid__c
                                    ,Rejection_Reason__c
                                    ,Task__c
                                    ,Translation__r.Name
                                    ,Translation__r.Estimated_Count__c
                                    ,Translation__r.Estimated_Units__c
                                    ,Translation__r.Source_Language__r.Name
                                    ,Translation__r.Target_Language__r.Name
                                    ,Translator_Price__c
                                    ,Translation__r.Currency__c
                                    ,Translation__r.Due_Date__c
                                    ,Translator__r.Name
                                    FROM Translation_Assignment__c
                                    WHERE Id = :id
                                    LIMIT 1];
    }
    
    public void intializeDocumentList() {

        String[] documentIdList = translationAssignment.Documents__c != null ? translationAssignment.Documents__c.split(';') : new String[]{};
        documentList = [SELECT Name
                        ,Url
                        FROM Document
                        WHERE Id IN : documentIdList
                        AND Url != null];   
    }
    
    ////////Pagereferences
    /////////////////////////////
     
    public PageReference accept() {
        translationAssignment.Assignment_Status__c = ReflexSettings.ASSIGNMENT_STATUS_ACCEPTED;
        try {
                update translationAssignment;
        } catch (system.exception e) {}

        // new chatter feed entry
        FeedItem post = new FeedItem();
        post.ParentId =  translationAssignment.Translation__c;
        post.Body = 'Translation has been accepted by ' 
                        + translationAssignment.Translator__r.Name;

        try {
            insert post;
        } catch (system.exception e) {}
                
        return null;
    }
    
    public PageReference reject() {
        translationAssignment.Assignment_Status__c = ReflexSettings.ASSIGNMENT_STATUS_REJECTED;
        try {
            update translationAssignment;
        } catch (system.exception e) {}
        
        // new chatter feed entry
        FeedItem post = new FeedItem();
        post.ParentId =  translationAssignment.Translation__c;
        post.Body = 'Translation has been rejected by ' 
                        + translationAssignment.Translator__r.Name 
                        + 'for the following reason: \n'
                        + translationAssignment.Rejection_Reason__c;
        try {
                insert post;
        } catch (system.exception e) {}
        return null;
    }  
    
    public PageReference sendChatterMessage() {
    // new chatter feed entry
        FeedItem post = new FeedItem();
        post.ParentId =  translationAssignment.Translation__c;
        post.Body = 'Message from '
                    + translationAssignment.Translator__r.Name 
                    + ' : '
                    + chatterMessage;
        //try {
            //new WithoutSharing().forceInsert(new FeedItem[]{post});
        //} catch (system.exception e) {}         
        chatterMessage = '';
        return null;    
    }  
}