src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <label>@DEPR Teljesítési státusz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nyitva</fullName>
                </value>
                <value>
                    <fullName>Fordítónak kiadva</fullName>
                </value>
                <value>
                    <fullName>Lektornak kiadva</fullName>
                </value>
                <value>
                    <fullName>Megrendelőnek leszállítva</fullName>
                </value>
                <value>
                    <fullName>Visszautasítva</fullName>
                </value>
                <value>
                    <fullName>Megrendelés törölve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>Rejection Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No translators available</fullName>
                </value>
                <value>
                    <fullName>Not expensive enough</fullName>
                </value>
                <value>
                    <fullName>Too much text</fullName>
                </value>
                <value>
                    <fullName>Unable to complete in deadline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <label>Megbízási státusz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kiadva</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Teljesítve</fullName>
                </value>
                <value>
                    <fullName>Megrendelés visszavonva</fullName>
                </value>
                <value>
                    <fullName>Megreklamálva</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rejection_Reason__c</fullName>
        <label>A reklamáció oka</label>
        <length>2500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Feladat</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Translating</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Proofreading</fullName>
                </value>
                <value>
                    <fullName>Editing</fullName>
                </value>
                <value>
                    <fullName>Supervising</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Fordítói megbízás</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translation Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TranslationAssignment_Rejected.cls
public class TranslationAssignment_Rejected extends TranslationAssignmentTrigger {
    
    public TranslationAssignment_Rejected(Translation_Assignment__c[] sobjectOldList, Translation_Assignment__c[] sobjectNewList) {
        super(sobjectOldList, sobjectNewList);
    }    
    
    public override Boolean getIsMatching(Translation_Assignment__c sobjectOld, Translation_Assignment__c sobjectNew) {
        return sobjectOld.Assignment_Status__c != ReflexSettings.ASSIGNMENT_STATUS_REJECTED &&  sobjectNew.Assignment_Status__c == ReflexSettings.ASSIGNMENT_STATUS_REJECTED;
    }    

    public override void execute(Translation_Assignment__c[] sobjectList, Boolean doUpdate) {
        Map<Id, User> userMap = new Map<Id, User>([SELECT Name
                                                    , Email 
                                                    FROM User]);
        
        Map <Id, Translation__c> translationMap = new Map <Id, Translation__c> ([SELECT Name 
                                                                                ,OwnerId
                                                                                FROM Translation__c]);  
                                                                                
        Map <Id, Translator__c>  translatorMap = new Map <Id, Translator__c>([SELECT Name
                                                                                FROM Translator__c]);
                                                                                                                                                                                                             
        Messaging.SingleEmailMessage[] mailList = new Messaging.SingleEmailMessage[]{};                                                                                 
        for (Translation_Assignment__c tra : sobjectList) {
            Set<String> toAddresses = New Set<String>();
            Translation__c translation = translationMap.get(tra.Translation__c);
            Id userId = translation.OwnerId;
            // the recepient
            toAddresses.add(userMap.get(userId).Email);
            
            Map<String, String> taskMap = new Map<String, String>{
            	'Translating' => 'fordítást',
            	'Proofreading' => 'lektorálást',
            	'Editing' => 'korrektúrát',
            	'Supervising' => 'editálást'
            };
             
            // the body   
            Map<String, String> fieldMap = new Map <String, String> {
            	'user_name' => userMap.get(userId).Name,
            	'translation_name' => translationMap.get(tra.Translation__c).Name,
            	'task' => taskMap.get(tra.Task__c),
            	'rejection_reason' => tra.Rejection_Reason__c == null ? '' : tra.Rejection_Reason__c,
            	'translator_name' => translatorMap.get(tra.Translator__c).Name
            };
            String emailBody = replacePlaceHolders(ReflexSettings.EMAIL_TEMPLATE_TASK_REJECTION, fieldMap);

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setUseSignature(false); 
            mail.setToAddresses(new List<String>(toAddresses));
            mail.setSubject('REFLEX: Lemondott munka -- ' + translation.Name);
            mail.setHtmlBody(emailBody);
            mailList.add(mail);    
        }
        
        try {
            Messaging.sendEmail(mailList);
        } catch (system.exception e) {}
       
    }
    
    public String replacePlaceHolders(String s, Map<String, String> fieldMap) {
        for (String key : fieldMap.keySet()) {
            s = s.replace('{{' + key + '}}', fieldMap.get(key));
        }
        return s;
    }    
}