src/objects/Translation__c.object
<CustomObject>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Quality__c</fullName>
        <label>@DEPR Quality</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipName>Translation_Feedbacks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipName>Translation_Feedbacks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fordítói Minősítés</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Translation Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fordítói Minősítések</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TranslationFeedbackTest.cls
@isTest
private with sharing class TranslationFeedbackTest {
    static testMethod void myTest1() {
       ReflexTests test = new ReflexTests();    
       test.initializeTranslation();
       test.insertTranslator();
       test.insertTranslationAssignment();
       test.insertLanguagePair();      
       Translation_Feedback__c tr = new Translation_Feedback__c();
       tr.Translation__c = test.getTranslation().id;
       tr.Translator__c = test.getTranslator().id;
       insert tr;
       tr.Quality__c = 4;
       update tr;
        
       
       SobjectExtension s = new SobjectExtension();
       s.testCheat();
       Translation_RollupAssignments x = new Translation_RollupAssignments(new Translation__c[]{}, new Translation__c[]{});
       x.testCheat();
       AssignmentNotificationController y = new AssignmentNotificationController();
       y.testCheat();       
       
       SobjectTrigger so = new SobjectTrigger(new Sobject[]{}, new Sobject[]{});
       so.execute();
       so.defaultZero(2);
        
       
       
       system.assert(true);
    }
}