src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <label>@DEPR Teljesítési státusz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nyitva</fullName>
                </value>
                <value>
                    <fullName>Fordítónak kiadva</fullName>
                </value>
                <value>
                    <fullName>Lektornak kiadva</fullName>
                </value>
                <value>
                    <fullName>Megrendelőnek leszállítva</fullName>
                </value>
                <value>
                    <fullName>Visszautasítva</fullName>
                </value>
                <value>
                    <fullName>Megrendelés törölve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Status__c</fullName>
        <label>Megbízási státusz</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Kiadva</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Teljesítve</fullName>
                </value>
                <value>
                    <fullName>Megrendelés visszavonva</fullName>
                </value>
                <value>
                    <fullName>Megreklamálva</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Fordítói megbízás</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translation Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <label>Másodlagos email</label>
        <type>Email</type>
    </fields>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Translation_StatusRejected.cls
public class Translation_StatusRejected extends TranslationTrigger {
	
    public Translation_StatusRejected(Translation__c[] sobjectOldList, Translation__c[] sobjectNewList) {
        super(sobjectOldList, sobjectNewList);
    }    
    
    public override Boolean getIsMatching(Translation__c sobjectOld, Translation__c sobjectNew) {
        return sobjectOld.Assignment_Status__c != ReflexSettings.ASSIGNMENT_STATUS_REJECTED &&	sobjectNew.Assignment_Status__c == ReflexSettings.ASSIGNMENT_STATUS_REJECTED;
    }    

    public override void execute(Translation__c[] sobjectList, Boolean doUpdate) {
        Map <Id,Translation_Assignment__c> traMap = new Map <Id,Translation_Assignment__c>([SELECT Name
                                                                                        ,Translation__c
										                                                ,Translator__r.Email__c
										                                                ,Translator__r.Secondary_Email__c
										                                                FROM Translation_Assignment__c
	           							                                                WHERE Translation__c IN :sobjectList]);
	    
	    Messaging.SingleEmailMessage[] mailList = new Messaging.SingleEmailMessage[]{};      							                                                
        for (Translation__c translation : sobjectList) {
        	// getting all the emails for the assigned translators
        	Set<String> toAddresses = new Set<String>();
        	for (Translation_Assignment__c tra : traMap.values()) {
        	    if (tra.Translation__c == translation.Id) {
        	        if (tra.Translator__r.Email__c != null) {
        	        	toAddresses.add(tra.Translator__r.Email__c);
        	        }   
                    if (tra.Translator__r.Secondary_Email__c != null) {
                        toAddresses.add(tra.Translator__r.Secondary_Email__c);
                    }           	        
        	    }	
        	}
        	
	        
	        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	        mail.setUseSignature(false); 
	        mail.setToAddresses(new List<String>(toAddresses));
	        mail.setSubject('REFLEX: Megszunt feladat --' + translation.Name);
	        mail.setHtmlBody('A kovetkezo feladat MEGSZUNT. ' + translation.Name);
	        mailList.add(mail);        	
        }
        
        system.debug('+++ MAILLIST ' + mailList);
        try {
            Messaging.sendEmail(mailList);
        } catch (system.exception e) {}
       
    }
}