src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Units__c</fullName>
        <label>Mennyiség</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>szóközzel növelt karakter</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>forrásnyelvi szó</fullName>
                </value>
                <value>
                    <fullName>characters</fullName>
                </value>
                <value>
                    <fullName>words</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Translation_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Estimated_Count__c</fullName>
        <label>Az ajánlat alapját képező mennyiség</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translation__c</fullName>
        <label>Megrendelés</label>
        <referenceTo>Translation__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Translator_Price__c</fullName>
        <label>Fordítói díj</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Translator__c</fullName>
        <label>Fordító</label>
        <referenceTo>Translator__c</referenceTo>
        <relationshipLabel>Fordítási megbízások</relationshipLabel>
        <relationshipName>Translation_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Fordítói megbízás</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translation Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Translator__c.object
<CustomObject>
    <label>Translator</label>
    <nameField>
        <label>Név</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Translators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TranslationAssignmentService.cls
public with sharing class TranslationAssignmentService {


	public static Translation_Assignment__c calculatePrice(Translation_Assignment__c ta, Translator__c tra) {

		// words or chars ?
		Boolean isWords = false;
		if (ta.Translation__r.Estimated_Units__c == ReflexSettings.TRANSLATION_ESTIMATED_UNITS_WORDS) {
			isWords = true;
		}

		// the unit price on translator level
		Decimal unitPrice = 0;
		if (tra != null) {
			if (!isWords && tra.Char_Price__c != null) {
				unitPrice = tra.Char_Price__c;
			} else if (isWords && tra.Word_Price__c != null) {
				unitPrice = tra.Word_Price__c;
			}
		}

		ta.Translator_Price__c = (ta.Estimated_Count__c != null ? ta.Estimated_Count__c : 0) 
								* unitPrice;
		return ta;
	}
}