src/objects/Translation__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Branch-Account record.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Branch</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Translations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Megrendelés</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>A megrendelés száma</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Megrendelések</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Translation_AssignToBranch.cls
public with sharing class Translation_AssignToBranch {
	private Translation__c[] sObjectNewList;
	
    public Translation_AssignToBranch(Translation__c[] sObjectOldList, Translation__c[] sObjectNewList) {
    	this.sObjectNewList = sObjectNewList;
    }
    
    public void execute() {
        Map<Id, User> userMap = new Map<Id, User>([SELECT Name,
                                                    UserRoleId
                                                    FROM User]); 
        Map<Id, UserRole> userRoleMap = new Map<Id, UserRole>([SELECT 
                                                                DeveloperName 
                                                                FROM UserRole]);                                        
        system.debug(userMap);
        system.debug(userRoleMap);
        
        for (Translation__c translation : sObjectNewList) {
        	if (userMap.get(translation.OwnerId).UserRoleId == null) {
        		continue;
        	}
        	String userRoleName = userRoleMap.get(userMap.get(translation.OwnerId).UserRoleId).DeveloperName;
            String branchId = ReflexSettings.getSettingValue('ROLE_TO_BRANCH_' + userRoleName);
            if(branchId != null) {
            	translation.Branch__c = branchId;
            }    
        }
    }
}